### ISSUE TITLE
Can't edit keylogger

### ISSUE THREAD

**Issue by SmoothSalad** [DarkSecDevelopers/HiddenEye#377]
Hi I want to modify the keylogger.js but every time I start the program the script resets and I don't know why (I want to change the script because when the keylogger is used in an android phone the keys appear "Undefined")

**Comment by sTiKyt** [comment]
@An0nUD4Y

**Comment by usama7628674** [comment]
Just dont use keylogger.Use 'N' when script asks to include keylogger.

**Comment by An0nUD4Y** [comment]
@SmoothSalad , I know this issue exist, If you wants to modify the keylogger ,

Before Editing the file change the permissions..
Use '' chmod 777 * ''

Now Just modify the webpages/keylogger.js file
Before launching the script.

This is happening with you because :
1) Either you are editing the server/www/keylogger.js file.
2) OR, You are Editing without Admin Privilege in your System.

**Comment by An0nUD4Y** [comment]
No Response. Closing Here..
Feel Free to Reopen.
