### ISSUE TITLE
Unable to launch multiple instances of HiddenEye

### ISSUE THREAD

**Issue by DocKali** [DarkSecDevelopers/HiddenEye#406]
Hi everyone,

I don't understand why, but when I try to launch two instances of HiddenEye, I can't. I setup the first campaign, generate the link, everything is ok. Then I begin to prepare the second campain in another window, but the first campagn crash... 

Here is the traceback I have : 

```
Traceback (most recent call last):
  File "HiddenEye.py", line 46, in <module>
    getCredentials(port)
  File "/opt/HiddenEye/Defs/Actions.py", line 604, in getCredentials
    with open('Server/www/ip.txt') as creds:
FileNotFoundError: [Errno 2] No such file or directory: 'Server/www/ip.txt'
```

Any idea where it comes from?

**Comment by An0nUD4Y** [comment]
@DocKali , You have to create a separate server folder for 2nd attack.
Do one thing , Create a new Hiddeneye Folder and try launching the new attack from that directory with different port.
I hope it will help.

**Comment by DocKali** [comment]
Thanks @An0nUD4Y, your solution is effective. I create a new folder and I can launch a new attack through it. As you specified, a different port need to be specified for each attack.

**Comment by DocKali** [comment]
Just a little problem with your soluce : The tool generate the exact same Ngrok links for the attacks. I need, two distincts links, how can I do that?

**Comment by An0nUD4Y** [comment]
@DocKali , Script is using Ngrok free version without any ngrok account & without any paid plan . Which has It's own limits. That's why a single user can get only one link per device.

But wait , If you still wanna use Ngrok you can signup and purchase a paid plan. 
Then you can configure the authentication token of Ngrok by launching '/server/ngrok' present in Hiddeneye Directory (At least once Script should be run to get the Ngrok file ) ...
To know more about NGROK
Read Here : https://ngrok.com/docs

**Comment by DocKali** [comment]
Thanks for this answer @An0nUD4Y, I'll have a look at Ngrok's paid plans. I could indeed solve my problem.

**Comment by usama7628674** [comment]
@DocKali Or use serveo random url

**Comment by DocKali** [comment]
Serveo is often black listed by mail and social platforms, this kind of link results in a red flag, not good for an attack....
If I pay a pro version of Ngrok, did HiddenEye let me use the news functionalities, especially personalized links?
Thanks for your answers @An0nUD4Y
