### ISSUE TITLE
Server/www/index.html : the file or directory does not exist 

### ISSUE THREAD

**Issue by uran86** [DarkSecDevelopers/HiddenEye#421]
Server/www/index.html : the file or directory does not exist 

The tool did work before. But now i get this when i use the cloudfare. 

Any solution to this? And why this issue?

Thanks in advance,

**Comment by An0nUD4Y** [comment]
@uran86 , It's a bug , because some templates like Microsoft contains the index.php as index file but when we wants to deploy the cloudfare it assumes that their is index.html file which has to be renamed and replaced..
Thanks to mention it .. I will fix it soon.

Steps you can try yourself, if needed the cloudfare page as index page.
1) Just start the script choose desired template and try to add cloudfare.
2) If shows that error , than try doing it manually, 
3) Just goto Server/www folder after completing the script.
4) And rename the index file to index2.html
And copy the webpage/cloudfare.html to server/www and rename it to index.php .

5) And Everything will start working.

OR 
Wait till we fix it.
