### ISSUE TITLE
API Service

### ISSUE THREAD

**Issue by max120788** [DarkSecDevelopers/HiddenEye#427]
Hi, can it be build as API service with Python.

**Comment by Moltivie** [comment]
Could you be more specific on what you are asking?
Thanks.

**Comment by Moltivie** [comment]
It has been a week since I have not got a reply back from the author.
To answer, the project itself is Open Source, so no need to build an API service.
People might contribute and customize their local project as they would like; and I consider this more then an API service.

I consider the Issue being answered and I'll close is. Do not hesitate to re-open it if further questions.

Thanks.
