### ISSUE TITLE
Every custom url with Serveo or Localxpose is invalid

### ISSUE THREAD

**Issue by Jsikkema1** [DarkSecDevelopers/HiddenEye#430]
**Describe the bug**
Every custom url with serveo or localxpose is invalid. I've tried it in kali, termux and userland. Even if i fill in a random word as computer of something it is invalid. A week ago it did work. Now it doesnt. 

**To Reproduce**
1. Facebook, google or anything
2. No keylogger, no cloudfare
3. Redirect = www.facebook.com
4. Port = 4444/8080
5. Choose: Localxpose or Serveo
6. Custom url
7. Anything gives the error

**Screenshots**
![Screenshot_20191110_215938_tech ula](https://user-images.githubusercontent.com/51862581/68550942-ef0b5180-0407-11ea-9aaa-e68d844caf6c.jpg)

**Desktop (please complete the following information):**

 - OS: kali linux on rpi 3b+
 

**Smartphone (please complete the following information):**
 - Device: huawei mate 20 lite
 - os: android 9

**Comment by An0nUD4Y** [comment]
@Jsikkema1 , Let me clear one thing..
Localxpose doesn't support termux.
And 
Before trying to create custom Url using serveo try using Random url and if random url is not also generating.
Then 
Check if serveo.net is Up or Down..
As due to maintance serveo sometimes goes offline.

Let us know what you observed.
And also please share ScreenShot of Linux or userland other than Termux so we can be more sure about issue.

**Comment by Jsikkema1** [comment]
That screenshot is in userland.

**Comment by Jsikkema1** [comment]
I get the exact same error in userland, ternux and kali on rpi
