### ISSUE TITLE
Login Question

### ISSUE THREAD

**Issue by Misko2468** [DarkSecDevelopers/HiddenEye#535]
Is their a way to get the victim logged in instead of redirecting and forcing them to re-enter their info?

Might have overlooked this, I was using Modshlika prior to this.

**Comment by An0nUD4Y** [comment]
@spmedia ,   Its  possible in Modlishka because they works as man in the middle attack by reverse proxying the requests between client and server. So they are able to verify credentials and gets the session. 
In our case we are simply grabbing any credentials and redirecting user. 
So for now its not possible to verify the inputs credentials  at tge real time.

**Comment by Misko2468** [comment]
Oh, ok I still like HiddenEye way more than, Blackeye or Modlishka, but do you know of any that have that ability?

**Comment by An0nUD4Y** [comment]
@Misko2468 , Evilginx2 will do it for you easily, You can refer my modified forked repo of evilginx2 here github.com/an0nud4y/evilginx2

**Comment by An0nUD4Y** [comment]
@Misko2468 , Their you can also find some basic error solutions in Evilginx.

**Comment by Misko2468** [comment]
Alright, Thanks Again!
