### ISSUE TITLE
Can't access phishing page thru local network

### ISSUE THREAD

**Issue by pispuso** [DarkSecDevelopers/HiddenEye#595]
**Describe the bug**
Hello! First of all, HiddenEye seems to work mostly without problems, I can use ngrok and access from 127.0.0.1 to test the site, but for some reason when I use LOCALHOST option I try to access thru my IP (ex. 192.162.0.5) but I can't access. Same thing happens no matter what PC in my network I use, even on the same PC where I'm running HiddenEye, for some reason, it does not connect using the local IP but it does using 127.0.0.1.

Just to check if I had something wrong on other end I tried my Apache server and it works as expected. I can connect thru local IP on any PC on my network, but HiddenEye does not work.

**To Reproduce**
Just try LOCALHOST option, no matter the port I use, it doesn't work.

**Expected behavior**
Be able to connect tru my local IP on any PC on my network.

**Desktop (please complete the following information):**
 - OS: Kali Rolling 2020.2
 - Raspberry Pi 4

**Comment by An0nUD4Y** [comment]
@pispuso , We are aware of this. 
We uses php server.. So in php server you if you have launched a server on 127.0.0.1:8080 and try to browse that server with address http://localhost:8080 it will not return anything.
Thats why this issue is occurring.
We will soon move to nginx server.

For now you can try using same ip everywhere to test.

**Comment by pispuso** [comment]
Oh that's it! Thanks for clearing up!
