### ISSUE TITLE
Not getting phising link

### ISSUE THREAD

**Issue by sidewinder0505** [DarkSecDevelopers/HiddenEye#613]
I am not able to get the link
the NGROK Link says the server is busy and none other is providing any link
![Screenshot 2020-05-27 12^%31^%38](https://user-images.githubusercontent.com/65846078/82988784-52ad4300-a017-11ea-91b1-caca2e5015f0.png)
python 3 version =3.8.3rc1
how to check hidden eye version?

**Comment by sTiKyt** [comment]
@sidewinder0505 give us screenshot

**Comment by sTiKyt** [comment]
@sidewinder0505 you can see version when you have to select page...

**Comment by Berus008** [comment]
localexpose will not work anymore try to run it in localhost by pagekite running as if in the localserver..

**Comment by Berus008** [comment]
@MenInBlack9981 see the fact is that these services are only run if you choose to buy them or trust them with their policy but however still you can run this script into your localserver instead of these services so that being you said you just need to open another terminal where you can run pagekte manually and then paste the pagekite link in the place of your local server address or if there's no paste option then you can simply run the pagekite first and then use the localserver option in hiddeneye and after choosing the local server you can use the pagekite link because it will appear as your chosen page for.

**Comment by MenInBlack9981** [comment]
any video tutorial available???

**Comment by Berus008** [comment]
@MenInBlack9981 no there's no video of these because this is the result of my experiment if u are a new user of Kali Linux then probably you will have a hard time to understand it...

**Comment by Berus008** [comment]
@MenInBlack9981 and one more thing always run it in root

**Comment by MenInBlack9981** [comment]
actually i m on termux without root

**Comment by gauravsingh06121** [comment]
Bro if you have hotspot on your system just turn it on....your will get tha link

**Comment by Berus008** [comment]
> 
> 
> Bro if you have hotspot on your system just turn it on....your will get tha link

does it even make any sense?

**Comment by sTiKyt** [comment]
My request for information wasn't responded, closing as offtopic
